# Generated by Django 4.1.3 on 2022-12-21 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_remove_conta_garcom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conta',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='conta',
            name='mesa',
        ),
        migrations.RemoveField(
            model_name='conta',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='conta',
            name='total',
        ),
        migrations.AlterField(
            model_name='conta',
            name='pagamento',
            field=models.CharField(max_length=80, verbose_name='Informe a forma de pagamento'),
        ),
    ]
